# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7']
        tox-env: ['py']
        include:
            - python-version: '3.5'
              tox-env: 'py35-nodeps'
            - python-version: '3.5'
              tox-env: 'py35-extra'
            - python-version: '2.7'
              tox-env: 'py27-extra'
            - python-version: '3.6'
              tox-env: 'py36-extra'
            - python-version: '3.6'
              tox-env: 'py36-legacy'
            - python-version: '3.7'
              tox-env: 'py37-nodeps'
            - python-version: '3.6'
              tox-env: 'mypy'
            - python-version: '3.6'
              tox-env: 'docs'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: tox
      run: |
        tox -e ${{ matrix.tox-env }}
